### PR TITLE
Fix bundle size

### PR DESCRIPTION
**Pull request by lydell**
I made a mistake in #12 when saying this:

> using the standard Node.js module 'url'. Next.js already uses it itself, so
> `require`ing it does not blow up the bundle size or anything (verified using
> next-bundle-analyzer).

I forgot to run `npm run build` in this repo when testing the new bundle size,
so my "before" and "after" results were identical! Doh!

As you can see at [bundlephobia], #12 _did_ bump up the size of the package
quite a lot (14 kB to 24 kB).

[bundlephobia]: https://bundlephobia.com/result?p=nextjs-dynamic-routes

This happens because `dist/` is compiled using webpack, pulling all dependencies
into the bundle.

This commit fixes the problem by only using babel to compile `dist/`, leaving
all `require` calls intact, letting Next.js' build take care of resolving and
bundling them. This lets Next.js share the same 'url' module both for itself and
for this package.

<details>
<summary>Size before this PR: 26.2 kB</summary>

screenshot from 2019-01-25 08-09-54

</details>

<details>
<summary>Size after this PR: 12.8 kB</summary>

screenshot from 2019-01-25 08-15-58

</summary>

Also, "loose mode" was turned on in .babelrc since it saves 1.5 kB and we don't
use any features that require the extra spec compliance anyway.

### CODE REVIEW

**Comment by gvergnaud** [comment]
I don't think it's going to work. This code is supposed to run in the browser as well as on the server, and the 'url' package won't be available in the browser window. I think we should just revert your change from #12  and add the the missing features to `parseUrl`. Could you do that instead of changing the build system? 
I should have thought about it, my bad.

**Comment by lydell** [comment]
It does work, I’ve tried it!

**Comment by gvergnaud** [comment]
I fixed the issue, actually it was just because of the config of webpack-node-externals. 

Here is the commit: https://github.com/gvergnaud/nextjs-dynamic-routes/commit/c92f1ae7692a9a5caf7fc0e75c8cee6fa593652b

You can see the result here: https://bundlephobia.com/result?p=nextjs-dynamic-routes@2.5.1

I'm closing your PR, because I'd like to keep webpack for now.

Thanks!

**Comment by lydell** [comment]
Nice! Just curios – is there are reason you want to keep webpack? Not using it saves another 0.5kB :)

**Pull request closed without merging**
